<?php 
	// Change the language name
	$language = "Language1";

	// Adapt the letters of the English alphabet categories to match the index files, e.g.
	// $lettersIndex = array("A", "B", "C", "D","E","F","G","H","I","J","K","L","M","N","O","P","Q","R","S","T","U","V","W","Y");
	$lettersIndex = array();

	// Adapt the letters of the language alphabet to match the lexicon files, e.g.
	// $lettersLexicon = array("A","E","G","I","J","K","L","Rl","M","N","Ny","Ng","Rn","P","Q","R","Rr","S","T","Rt","U","W","X","Y");
	$lettersLexicon = array();

	// Enter the names of the top-level categories and the number of the file they are contained in
	// To do this, you will have to manually go through the category files generated by LexiquePro, e.g.
  	//  $categoryNames = array(
	//    1=> "Land",
	//    8=> "Environment",
	//    13=>  "Water",
	//    ...
	//    169=> "Ritual and socery"
  	//  );
  	$categoryNames = array();

    // Set the address of the home page from where the dictionary was linked to 
    $homepage = "";

    // **********************************************
	// Do not change any variables below this comment
	// **********************************************
	
  	// Set the finder index language
  	$indexLanguage = "English";

	// file names
	$lexicon = "lexicon.php";
	$finder = "index-english.php";
	$categories = "categories.php";
	$search = "search.php";

	$pages;
	$names;

	if(empty($homepage)){
		$pages = array($lexicon, $finder, $categories, $search);
		$names = array($language, $indexLanguage, "Categories", "Search");
	} else {
		$pages = array($homepage, $lexicon, $finder, $categories, $search);
		$names = array("Home", $language, $indexLanguage, "Categories", "Search");
	}

	$active = " class=\"active\"";

?>
